### ISSUE TITLE
Use OpenCV module methods on GDScript

### ISSUE THREAD

**Issue by BalasaravananCM** [swarnimarun/godot#3]

**Comment by swarnimarun** [comment]
![image](https://user-images.githubusercontent.com/19930870/53907885-21440280-4074-11e9-9df0-17d6a2d66fff.png)

Partial work done.

It opens a default image for now just as a test.

**Comment by swarnimarun** [comment]
Also this also includes #2

**Comment by swarnimarun** [comment]
![image](https://user-images.githubusercontent.com/19930870/54152663-c6d7e700-4463-11e9-9832-2d9888f6ad5f.png)

So this can get us results,
![image](https://user-images.githubusercontent.com/19930870/54152988-82008000-4464-11e9-8d03-2dfd119d018c.png)
